apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: docker.io/siddhartha0709/product-service:2a59ccb7c821a06df45bb221ed76d7f2c2e61689
          ports:
            - containerPort: 3002
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/product-db
            - name: ALLOWED_ORIGIN
              value: "*"
