apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: docker.io/siddhartha0709/cart-service:f5d27361df199104a4696e23f02ef913d76f92c3
        ports:
        - containerPort: 3003
        env:
         - name: MONGO_URI
           value: mongodb://mongo:27017/cart-db
         - name: ALLOWED_ORIGIN
           value: "*"
